### ISSUE TITLE
Not receiving sflow even though UDP requests are incoming

### ISSUE THREAD

**Issue by simPod** [cloudflare/goflow#10]
Running 2.0.4
```
./goflow -v
GoFlow v2.0.4
```

When started no flows are being displayed

```
./goflow -loglevel=debug  -kafka=false -netflow=false -sport=9992
INFO[0000] Starting GoFlow                               NetFlow=false sFlow=true
DEBU[0000] Starting workers                              Name=sFlow
INFO[0000] Listening on UDP :9992                        Type=sFlow
```

However when I run `tcpdump -i enp175s0f1 udp and port 9992` I can see that sflow data are coming from that device through UDP.

Am I doing something wrong?

**Comment by lspgn** [comment]
Hi Simon,
Any chances I could look at the flows?

Does `netstat -tulpn | grep 9992` returns goflow?

**Comment by simPod** [comment]
Tried with p (`UDP listen needs -p arg`)

```
nc -lup 9992 > data.bin
Can't grab 0.0.0.0:9992 with bind
```

**Comment by simPod** [comment]
That was because the goflow was running. When I stop goflow, it outputs nothing 🤔

**Comment by simPod** [comment]
Indeed it was. Thanks for help, much appreciated!
