### ISSUE TITLE
How to lookup the received netflow packets

### ISSUE THREAD

**Issue by StefanoKoo** [cloudflare/goflow#100]
Thanks for your great projects.
I made netflow packets through netflow packet generator to check if my kafka consumer received successfully received data.
However, I can't deserialize the contents that my consumer console shows me.
Can your console show the specific data of the netflow packets?

**Comment by lspgn** [comment]
Hi @StefanoKoo,
You cannot deserialize in the console without a protobuf decoder. I invite you to have a look at Google's guides ([eg: for Java](https://developers.google.com/protocol-buffers/docs/javatutorial))
[Goflow2](https://github.com/netsampler/goflow2) fork has an option to send JSON into Kafka.

**Comment by StefanoKoo** [comment]
@lspgn Thanks for another great code.
