### ISSUE TITLE
Can this project be used as a library?

### ISSUE THREAD

**Issue by jsirianni** [cloudflare/goflow#101]
I have a use-case where I need to embed this project into another project, with no need for a Kafka (or other message queue) backend. 

Is this project designed with this use-case in mind?

**Comment by lspgn** [comment]
Hello,
Yes entirely. Although you should look at  https://github.com/netsampler/goflow2/blob/main/cmd/goflow2/main.go which features some changes to make it more flexible (transports/formats... are an import).

**Comment by slrtbtfs** [comment]
I recently used this project as a library in a program that doesn't use Kafka and instead puts the received flow messages in a custom pipeline, so I can confirm that this is possible and works quite well.

If you have further questions feel free to ask me. (I think my github profile has a public Email)
