### ISSUE TITLE
Renormalise the  sampled data

### ISSUE THREAD

**Issue by vishnubraj** [cloudflare/goflow#102]
I am sending the goflow received data to a cloud-based Syslog server for analysis. 
I am sending a sampled NetFlow data from the router to gofow, does the goflow output a normalized NetFlow data or I need to apply any calculation to normalize it?

if yes, multiplying the bytes with the sampling rate is enough? What is the formula used for this?

**Comment by lspgn** [comment]
Hello,
GoFlow does not do anything besides converting the data that is provided in the samples.
You are provided with the sampling rate but you need to apply the normalization in your tools.
Additionally, I believe most of the implementations are taking a per-packet per interface sampling. AFAIK there is no field that identify alternative methods of sampling (eg: sampling per distinct IP).

A simple case can be 
`Bytes * SamplingRate`

**Comment by vishnubraj** [comment]
Thanks for the clarification @lspgn  !!
