### ISSUE TITLE
Vlan id, no dst+src vlan

### ISSUE THREAD

**Issue by simPod** [cloudflare/goflow#11]
I was comparing flows received by this library and by nfcapd. It seems to me that in [VlanId](https://github.com/cloudflare/goflow/blob/c4939ad960f8672bcb2d8a1b26d68841a11170e3/pb/flow.proto#L74) is the same content as would normally be in srcVlan field. Why is goflow designed to have VlanId only and not both src+dst vlan?

**Comment by lspgn** [comment]
I started implementing this setting with sFlow, which only shows the current 802.1q VLAN.
I'm assuming you're using NetFlow/IPFIX. Do you have samples I could use? Or could you give me the field IDs you're seeing?

Thank you

**Comment by simPod** [comment]
In nfdump, the fields are `%svln` and `%dvln` (caught by sfcapd, not nfcap). About the samples I'm sending you the email.

**Comment by lspgn** [comment]
I was thinking of the field id in the protocol specification.
Thank you!

**Comment by lspgn** [comment]
58 and 59 sounds indeed like default IPFIX https://www.iana.org/assignments/ipfix/ipfix.xhtml
Will implement it.

**Comment by lspgn** [comment]
Added vlan fields in the protobuf (https://github.com/cloudflare/goflow/commit/dbb683ec187caaf19e420ce55c0a8d1984c62658).

Feel free to re-open if there is any issue.
