### ISSUE TITLE
Invalid value?

### ISSUE THREAD

**Issue by simPod** [cloudflare/goflow#12]
Should here https://github.com/cloudflare/goflow/blob/master/pb/flow.proto#L15 be a value from `FlowType` enum, for example `0` rather than `1` which is not defined in that type?

If it is so I'll send PR

**Comment by lspgn** [comment]
Actually, it's the protobuf definition: it's not a [default value](https://developers.google.com/protocol-buffers/docs/proto#optional) but an identifier of the field (default is 0 in this case).

When decoding the protobuf without the schema, you will get something like `field 1 = 9`, but with a schema `FlowType = 9`.

**Comment by simPod** [comment]
Ah right, my bad. Thanks!
