### ISSUE TITLE
Flink code example?

### ISSUE THREAD

**Issue by nim-nim** [cloudflare/goflow#18]
Hi,

Is the flink code used to process the result published somewhere? Probably not to use it as-is (our big data guys want to use spark not flink) but to get some ideas. The RIPE presentations are awfully nice (thank you so much for them) but actual code examples would be better.

**Comment by lspgn** [comment]
Hi @nim-nim, apologies for the delay in my response.
Thank you for looking at the presentation!
We ended up discarding Flink part as [Clickhouse offers aggregations](https://clickhouse.yandex/docs/en/operations/table_engines/materializedview/) and the cluster was hard to maintain.
For everything that needs a more "live" aggregation: we turned to a Go program that inserts into Redis.
I still have the code and will publish it to the following [repo](https://github.com/cloudflare/flow-pipeline).
I have not tried Spark though.

Good luck!
