### ISSUE TITLE
DstIf/SrcIf vs InIf/OutIf naming

### ISSUE THREAD

**Issue by simPod** [cloudflare/goflow#28]
Hi, what is the reason for naming fields as DstIf and SrcIf? So far I have seen InIf and OutIf naming for the same thing. Thanks!

**Comment by lspgn** [comment]
Mostly consistency with other fields (source IP, source port...). But no other reasons.
Is it causing conflicts?

**Comment by simPod** [comment]
@lspgn Thanks for response! No conflicts. But it's usually called `input` and `output` so I wonder that it might be confusing. Also, src and dst fields represent something else in flow. Those are really info about packet's source and destination but inif and outif represent interfaces on the device where the flow is recorded. WDYT?

**Comment by AntoineThebaud** [comment]
Hello, I agree on this one, even more considering the name of the corresponding fields for NetFlow

```
SrcIf | ... | input  | ...| INPUT_SNMP (10)  | ...
DstIf | ... | output | ... | OUTPUT_SNMP (14) | ...
```

**Comment by lspgn** [comment]
Coming back to this a bit late.
This makes sense, I will change the protobuf field names (or feel free to PR).
Though I was not very eager to change the data structure since some people may use this as a library (but as long as I keep the IDs the same it is fine).

**Comment by simPod** [comment]
👍 I'll look into it. Releasing with proper version bump should then be IMO k.
