### ISSUE TITLE
Ip address after deserialized unreadable

### ISSUE THREAD

**Issue by lorierp** [cloudflare/goflow#29]
I'm having a problem. After deserialized NetFlow v9 from Kafka I get unreadable string.
For example
SrcIP: "dA\004\334"
DstIP: "^d\256\305"

If i try get byteArray from SrcIP then i get array byte who content 4 number. For example [100, 65, 4, -36]

I using protoc v3.8.0 for generate java class from .proto

**Comment by lspgn** [comment]
Hello,
IPs are stored as bytes arrays.
You have to convert them into an InetAddress before serializing them.

Thank you
