### ISSUE TITLE
Netflow errors

### ISSUE THREAD

**Issue by aiesam** [cloudflare/goflow#30]
I get the following error when trying to run

./goflow.go:66:2: undefined: initMetrics
./goflow.go:109:2: undefined: NetFlowTemplatesStats
./goflow.go:157:4: undefined: NetFlowErrors
./goflow.go:164:4: undefined: NetFlowErrors
./goflow.go:171:4: undefined: NetFlowErrors
./goflow.go:178:4: undefined: NetFlowErrors
./goflow.go:192:3: undefined: NetFlowStats
./goflow.go:202:5: undefined: NetFlowSetStatsSum
./goflow.go:210:5: undefined: NetFlowSetRecordsStatsSum
./goflow.go:219:5: undefined: NetFlowSetStatsSum
./goflow.go:219:5: too many errors

I am not sure why

**Comment by lspgn** [comment]
You need go type `go run goflow.go metrics.go`.
This will be fixed in version 3 (change the branch).

**Comment by aiesam** [comment]
Thanks. I tried it and it works. Will keep on experimenting. Thanks once again.
