### ISSUE TITLE
Failed to start the container

### ISSUE THREAD

**Issue by Krishjs** [cloudflare/goflow#42]
While running the command docker run --net=host -ti cloudflare/goflow:latest -kafka=false
INFO[0000] Starting GoFlow
INFO[0000] Listening on UDP :2056                        Type=NetFlowLegacy
INFO[0000] Listening on UDP :6343                        Type=sFlow
INFO[0000] Listening on UDP :2055                        Type=NetFlow
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c93a6]

goroutine 11 [running]:
github.com/cloudflare/goflow/utils.UDPRoutine(0xa06284, 0x7, 0xc000051420, 0x1, 0x0, 0x0, 0x807, 0x0, 0xac2760, 0xc000064960, ...)
        /build/utils/utils.go:164 +0xff6
github.com/cloudflare/goflow/utils.(*StateNetFlow).FlowRoutine(0xc000020e00, 0x1, 0x0, 0x0, 0x807, 0x0, 0x2, 0x0)
        /build/utils/netflow.go:348 +0x15a
main.main.func2(0xc000020e00, 0xc0000268a0)
        /build/cmd/goflow/goflow.go:129 +0x21b
created by main.main
        /build/cmd/goflow/goflow.go:124 +0x3e3

**Comment by lspgn** [comment]
@Krishjs: are you sending flows to it?

Could you tell me the version? It seems to work for me on `GoFlow v3.2.0 (2019-09-30T15:43:12-0700)`
