### ISSUE TITLE
Add support for ntopng (JSON over ZMQ)

### ISSUE THREAD

**Issue by synfinatic** [cloudflare/goflow#60]
Not everyone wants to submit stats using pbufs over kafka- sometimes you just want to use something off the shelf like https://www.ntop.org/products/traffic-analysis/ntop/

**Comment by lspgn** [comment]
Unfortunately, this is a too specific/branded change for this repo.
This is a good use case to use GoFlow as an external library though.

Gave more details on the attached PR: https://github.com/cloudflare/goflow/pull/61#issuecomment-582599784
