### ISSUE TITLE
Latest release not published in dockerhub

### ISSUE THREAD

**Issue by shyam334** [cloudflare/goflow#64]
Hello,

The latest release (v3.4.0) doesn't seem to be published in [dockerhub](https://hub.docker.com/r/cloudflare/goflow/tags).
Could anyone look into this.

**Comment by lspgn** [comment]
Woops, I didn't update it. Will do v3.4.1 including your PR.

**Comment by lspgn** [comment]
Added: https://hub.docker.com/layers/cloudflare/goflow/v3.4.1/images/sha256-4cf98d7f58d2e6232b246954480a864a74ea6d6e311f42f047530b6cddfa9579?context=explore
