### ISSUE TITLE
protobuf messages in the length-delimited format

### ISSUE THREAD

**Issue by bad3bs** [cloudflare/goflow#65]
It's will be awesome to add option to enable protobuf messages in the length-delimited format. That for native support clickhouse protobuf input (https://clickhouse.tech/docs/en/interfaces/formats/#protobuf).

**Comment by lspgn** [comment]
This is a good idea.
Attached a PR.
I'm not sure the protobuf can be mapped 1:1 within Clickhouse (example: storing src/dst IP addresses as bytes instead of two columns being a UInt32 and a FixedString(16)).
But I tested locally (fed from a Kafka), it works.

**Comment by lspgn** [comment]
Added the functionality. I also updated [flow-pipeline](https://github.com/cloudflare/flow-pipeline) to provide a functioning example with [Clickhouse](https://github.com/cloudflare/flow-pipeline/blob/master/compose/clickhouse/create.sh).
