### ISSUE TITLE
Data race in utils/netflow.go

### ISSUE THREAD

**Issue by davmatjo** [cloudflare/goflow#82]
When running goflow with the workers flag set to greater than 1, the application will sometimes crash due to a concurrent map read and write.

Running goflow with `go build -race` also highlights many data races in the same places.

I believe the issue is in utils/netflow.go `DecodeFlow()` where templates and sampling can be written to when only a RLock has been acquired from the RWMutex.

**Comment by lspgn** [comment]
I'll have a look! Thank you for the report
