### ISSUE TITLE
Support output formats other than protobuf over Kafka

### ISSUE THREAD

**Issue by sjwang90** [cloudflare/goflow#88]
### Background/Use Case
InfluxData's Telegraf project received a request (influxdata/telegraf#8425) to integrated into goFlow for IPFIX/NetFlow support. Currently Telegraf does not support binary (ex: protobuf) formats.

### Feature Request
Request for vFlow to add one of the [following output formats](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md) to ease the integration with Telegraf.
- InfluxDB Line Protocol
- Carbon2
- Graphite
- JSON
- Prometheus
- SplunkMetric
- Wavefront
- ServiceNow Metrics

Also not sure if goFlow is meant to be embedded in other programs as there might not be a stable library API for other programs use.

**Comment by lspgn** [comment]
@sjwang90 thanks! I added a comment on the telegraf thread.
GoFlow can be extended but the main format in this repository is Kafka+protobuf (or JSON).
For Influx/Telegraf, you will likely need aggregation.

**Comment by sjwang90** [comment]
Ok thanks for your feedback @lspgn. I'll close this issue for now.
