### ISSUE TITLE
Is this project alive ?

### ISSUE THREAD

**Issue by romchi** [cloudflare/goflow#97]
Hi, 

it is clear that there is interest in the project and there are pull requests, but it is not visible that these commits were accepted from the upstream side

**Comment by lspgn** [comment]
Hi @romchi,
Thank you for your interest.
I was maintaining this project at Cloudflare until I left the company in February.
I have been following some of the pull-requests/issues and new use-cases but haven't had time to update yet.
Additionally, I lost some accesses to specific namespace (eg: Dockerhub) so releasing would be more complex.
What I may do: I will likely spawn a new org+repo. This would also allow to do a cleanup in the code.
Please stay tuned. Sorry it's taking long.

**Comment by SuperQ** [comment]
Thanks for the update @lspgn. Let me know if there's anything I can do to help out.

**Comment by SuperQ** [comment]
Ping @lspgn, any progress on getting this project moved to a separate org? Anything I can help with?
